version: '3'

services:
   nginx:
     image: nginx:1.13-alpine
     container_name: nginx01
     ports:
       - "8001:8001"
     volumes:
       - ./project/explorer:/src
       - ./config/nginx:/etc/nginx/conf.d
     depends_on:
       - web
   web:
     build: .
     container_name: explorer
     command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn explorer.wsgi -b 0.0.0.0:8001"
     volumes:
       - ./project/explorer:/src
     expose:
       - "8001"
     restart: always
