# Generated by Django 2.0.7 on 2018-07-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20180707_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorDataCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=256)),
                ('special', models.CharField(blank=True, max_length=32, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=64, unique=True)),
                ('created_for', models.CharField(blank=True, choices=[('a', 'a'), ('admin', 'admin'), ('ahmetrasit', 'ahmetrasit'), ('b', 'b'), ('c', 'c')], max_length=256, null=True)),
                ('access_list', models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=2048)),
                ('description', models.CharField(max_length=2048)),
                ('status', models.CharField(choices=[('tested', 'tested'), ('experimental', 'experimental')], max_length=256)),
                ('special', models.CharField(max_length=256)),
                ('script', models.TextField()),
                ('creator_username', models.CharField(max_length=256)),
                ('subfolder_path', models.CharField(max_length=256)),
                ('dependencies', models.TextField()),
                ('input_major_data_category', models.CharField(max_length=128)),
                ('output_major_data_category', models.CharField(max_length=128)),
                ('minor_data', models.CharField(max_length=256)),
                ('one_or_many_input_files', models.CharField(max_length=32)),
                ('score', models.CharField(max_length=256)),
                ('key_value', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='intro_message',
            field=models.CharField(max_length=256),
        ),
    ]
