# Generated by Django 2.0.7 on 2018-07-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20180716_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='creator_username',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='step',
            name='created_for',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('ahmetrasit', 'ahmetrasit'), ('b', 'b'), ('c', 'c')], max_length=256, null=True),
        ),
    ]
