# Generated by Django 2.0.7 on 2018-07-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20180717_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='no_of_outputs',
            field=models.CharField(choices=[('one', 'one'), ('many', 'many')], default='one', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='sample_schema',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='special',
            field=models.CharField(choices=[('regular', 'regular'), ('upload', 'upload'), ('public', 'public'), ('other', 'other')], max_length=256),
        ),
    ]
