# Generated by Django 2.0.7 on 2018-07-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20180720_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='output_major_data_category',
            field=models.CharField(choices=[('fastq', 'fastq'), ('fastq.gz', 'fastq.gz')], max_length=128),
        ),
    ]
