# Generated by Django 2.0.2 on 2018-07-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_step_input_output_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_short_name', models.CharField(max_length=64, unique=True)),
                ('reference_description', models.CharField(max_length=2048)),
                ('reference_type', models.CharField(max_length=64)),
                ('placeholder', models.CharField(max_length=256)),
                ('script', models.TextField()),
                ('status', models.CharField(max_length=256)),
                ('special', models.CharField(max_length=256)),
                ('created_by', models.CharField(max_length=256)),
                ('subfolder_path', models.CharField(max_length=256)),
                ('dependencies', models.TextField()),
                ('score', models.CharField(max_length=256)),
                ('key_value', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='step',
            name='input_output_relationship',
            field=models.CharField(choices=[('1:1', '1 input file for 1 output'), ('1:*', '1 input file processed for many outputs'), ('*>1', 'many input files for 1 output'), ('*>*', 'many input files processed together for many outputs'), ('*:*', 'Each input file corresponds to an individual output')], max_length=128),
        ),
        migrations.AlterField(
            model_name='step',
            name='no_of_outputs',
            field=models.CharField(choices=[('one', 'one output per one input file'), ('many', 'many outputs of the same kind')], max_length=64),
        ),
    ]
