# Generated by Django 2.0.2 on 2018-07-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20180724_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='status',
            new_name='completed',
        ),
    ]
