# Generated by Django 2.0.2 on 2018-07-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20180724_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='reference_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='reference_short_name',
            new_name='short_name',
        ),
    ]
