# Generated by Django 2.0.2 on 2018-07-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20180724_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='one_or_many_input_files',
        ),
        migrations.AlterField(
            model_name='step',
            name='created_for',
            field=models.CharField(blank=True, choices=[('user', 'user')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='output_major_data_category',
            field=models.CharField(choices=[('bam', 'bam'), ('fastq', 'fastq'), ('fastq.gz', 'fastq.gz'), ('sam', 'sam')], max_length=128),
        ),
        migrations.AlterField(
            model_name='step',
            name='special',
            field=models.CharField(choices=[('regular', 'regular'), ('upload', 'upload'), ('other', 'other')], max_length=256),
        ),
    ]
