# Generated by Django 2.0.7 on 2018-07-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20180725_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField()),
                ('protocol_id', models.IntegerField()),
                ('process_id', models.IntegerField()),
                ('retry_of', models.IntegerField(blank=True, null=True)),
                ('depends_on', models.IntegerField(blank=True, null=True)),
                ('input_file', models.TextField()),
                ('script', models.TextField()),
                ('folder_path', models.TextField()),
                ('major_types', models.TextField()),
                ('minor_types', models.TextField(blank=True, null=True)),
                ('save_outputs_zipped', models.CharField(max_length=64)),
                ('created_by', models.CharField(max_length=256)),
                ('created_for', models.CharField(blank=True, max_length=256, null=True)),
                ('created_on', models.CharField(max_length=64)),
                ('started_on', models.CharField(blank=True, max_length=64, null=True)),
                ('finished_on', models.CharField(blank=True, max_length=64, null=True)),
                ('is_last', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('finished_status', models.CharField(blank=True, max_length=64, null=True)),
                ('retries_left', models.IntegerField()),
                ('special', models.CharField(blank=True, max_length=64, null=True)),
                ('key_value', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
