# Generated by Django 2.0.2 on 2018-07-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_datapoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='short_name',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='sample_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
