# Generated by Django 2.0.2 on 2018-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20180731_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='input_files',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='key_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='output_files',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='source_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
