# Generated by Django 2.0.2 on 2018-08-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20180731_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='script',
            new_name='complete_script',
        ),
        migrations.AddField(
            model_name='task',
            name='semi_complete_script',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='created_for',
            field=models.CharField(blank=True, choices=[('ahmet', 'ahmet')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='output_major_data_category',
            field=models.CharField(choices=[('counts.fa', 'counts.fa'), ('csv', 'csv'), ('fa', 'fa'), ('fastq.gz', 'fastq.gz'), ('sam', 'sam')], max_length=128),
        ),
    ]
