# Generated by Django 2.0.2 on 2018-08-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_auto_20180803_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_last',
        ),
        migrations.AlterField(
            model_name='task',
            name='protocol_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
