# Generated by Django 2.0.2 on 2018-08-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_auto_20180803_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='process_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
