# Generated by Django 2.0.7 on 2018-08-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_auto_20180803_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='status',
            field=models.CharField(default='waiting', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='output_major_data_category',
            field=models.CharField(choices=[('csv', 'csv'), ('fasta', 'fasta'), ('fastq.gz', 'fastq.gz'), ('sam', 'sam')], max_length=128),
        ),
    ]
