# Generated by Django 2.0.7 on 2018-08-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20180815_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='folder_path',
            new_name='starting_folder_path',
        ),
        migrations.AddField(
            model_name='task',
            name='target_folder_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='temporary_folder_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
