# Generated by Django 2.0.7 on 2018-08-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_auto_20180817_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='input_file',
            new_name='input_files',
        ),
    ]
