# Generated by Django 2.0.7 on 2018-07-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=32)),
                ('intro_message', models.TextField()),
                ('cpu_ratio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ram_ratio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('key_value', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
