# Generated by Django 2.0 on 2018-07-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainconfiguration',
            name='intro_message',
            field=models.CharField(max_length=256),
        ),
    ]
