# Generated by Django 2.0.7 on 2018-07-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20180707_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='key_value',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='special',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='speed',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
