# Generated by Django 2.0.7 on 2018-07-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20180707_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='speed',
            new_name='credit',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('bioinformatician', 'bioinformatician'), ('scientist', 'scientist'), ('intern', 'intern'), ('other', 'other'), ('boss', 'boss')], default=None, max_length=128, null=True),
        ),
    ]
